[2022-09-05 14:34:08,014] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: create_tables.test scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-09-05 14:34:10,353] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: create_tables.test scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-09-05 14:34:10,377] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 14:34:10,439] {taskinstance.py:1377} INFO - Starting attempt 9 of 9
[2022-09-05 14:34:10,549] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 14:34:21,319] {taskinstance.py:1397} INFO - Executing <Task(MySqlOperator): test> on 2022-09-01 00:00:00+00:00
[2022-09-05 14:34:24,293] {standard_task_runner.py:52} INFO - Started process 1217 to run task
[2022-09-05 14:34:24,317] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'create_tables', 'test', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '133', '--raw', '--subdir', 'DAGS_FOLDER/create.py', '--cfg-path', '/tmp/tmpjttrt3cw', '--error-file', '/tmp/tmpf0jzfc2y']
[2022-09-05 14:34:24,377] {standard_task_runner.py:80} INFO - Job 133: Subtask test
[2022-09-05 14:34:30,329] {task_command.py:371} INFO - Running <TaskInstance: create_tables.test scheduled__2022-09-01T00:00:00+00:00 [running]> on host cdeef4137858
[2022-09-05 14:34:33,365] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=create_tables
AIRFLOW_CTX_TASK_ID=test
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=9
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-09-05 14:34:33,398] {mysql.py:82} INFO - Executing: SHOW VARIABLES LIKE "secure_file_priv";
[2022-09-05 14:34:34,649] {base.py:68} INFO - Using connection ID 'mysql_conn_id' for task execution.
[2022-09-05 14:34:40,018] {dbapi.py:231} INFO - Running statement: SHOW VARIABLES LIKE "secure_file_priv";, parameters: None
[2022-09-05 14:34:40,223] {dbapi.py:239} INFO - Rows affected: 1
[2022-09-05 14:34:40,513] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=create_tables, task_id=test, execution_date=20220901T000000, start_date=20220905T143409, end_date=20220905T143440
[2022-09-05 14:34:42,017] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-05 14:34:42,752] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
