[2022-09-05 14:26:13,233] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: create_tables.test scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-09-05 14:26:13,408] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: create_tables.test scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-09-05 14:26:13,409] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 14:26:13,409] {taskinstance.py:1377} INFO - Starting attempt 8 of 8
[2022-09-05 14:26:13,418] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 14:26:13,554] {taskinstance.py:1397} INFO - Executing <Task(MySqlOperator): test> on 2022-09-01 00:00:00+00:00
[2022-09-05 14:26:13,598] {standard_task_runner.py:52} INFO - Started process 897 to run task
[2022-09-05 14:26:13,619] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'create_tables', 'test', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '116', '--raw', '--subdir', 'DAGS_FOLDER/create.py', '--cfg-path', '/tmp/tmpzemkkvru', '--error-file', '/tmp/tmpesjizn4h']
[2022-09-05 14:26:13,628] {standard_task_runner.py:80} INFO - Job 116: Subtask test
[2022-09-05 14:26:14,809] {task_command.py:371} INFO - Running <TaskInstance: create_tables.test scheduled__2022-09-01T00:00:00+00:00 [running]> on host cdeef4137858
[2022-09-05 14:26:15,444] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=create_tables
AIRFLOW_CTX_TASK_ID=test
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=8
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-09-05 14:26:15,460] {mysql.py:82} INFO - Executing: SHOW VARIABLES LIKE "secure_file_priv";
[2022-09-05 14:26:15,528] {base.py:68} INFO - Using connection ID 'mysql_conn_id' for task execution.
[2022-09-05 14:26:29,826] {dbapi.py:231} INFO - Running statement: SHOW VARIABLES LIKE "secure_file_priv";, parameters: None
[2022-09-05 14:26:32,128] {dbapi.py:239} INFO - Rows affected: 1
[2022-09-05 14:26:32,494] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=create_tables, task_id=test, execution_date=20220901T000000, start_date=20220905T142613, end_date=20220905T142632
[2022-09-05 14:26:33,461] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-05 14:26:34,642] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
