[2022-09-05 14:38:16,829] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: create_tables.test scheduled__2022-09-02T00:00:00+00:00 [queued]>
[2022-09-05 14:38:16,869] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: create_tables.test scheduled__2022-09-02T00:00:00+00:00 [queued]>
[2022-09-05 14:38:16,870] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 14:38:16,871] {taskinstance.py:1377} INFO - Starting attempt 10 of 10
[2022-09-05 14:38:16,884] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 14:38:17,027] {taskinstance.py:1397} INFO - Executing <Task(MySqlOperator): test> on 2022-09-02 00:00:00+00:00
[2022-09-05 14:38:17,037] {standard_task_runner.py:52} INFO - Started process 1397 to run task
[2022-09-05 14:38:17,044] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'create_tables', 'test', 'scheduled__2022-09-02T00:00:00+00:00', '--job-id', '150', '--raw', '--subdir', 'DAGS_FOLDER/create.py', '--cfg-path', '/tmp/tmpbc60_phr', '--error-file', '/tmp/tmpssas_ah5']
[2022-09-05 14:38:17,049] {standard_task_runner.py:80} INFO - Job 150: Subtask test
[2022-09-05 14:38:17,365] {task_command.py:371} INFO - Running <TaskInstance: create_tables.test scheduled__2022-09-02T00:00:00+00:00 [running]> on host cdeef4137858
[2022-09-05 14:38:17,823] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=create_tables
AIRFLOW_CTX_TASK_ID=test
AIRFLOW_CTX_EXECUTION_DATE=2022-09-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=10
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-02T00:00:00+00:00
[2022-09-05 14:38:17,827] {mysql.py:82} INFO - Executing: SHOW VARIABLES LIKE "secure_file_priv";
[2022-09-05 14:38:17,871] {base.py:68} INFO - Using connection ID 'mysql_conn_id' for task execution.
[2022-09-05 14:38:18,230] {dbapi.py:231} INFO - Running statement: SHOW VARIABLES LIKE "secure_file_priv";, parameters: None
[2022-09-05 14:38:18,912] {dbapi.py:239} INFO - Rows affected: 1
[2022-09-05 14:38:19,003] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=create_tables, task_id=test, execution_date=20220902T000000, start_date=20220905T143816, end_date=20220905T143819
[2022-09-05 14:38:19,145] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-05 14:38:19,341] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
